version: 2
updates:
  - package-ecosystem: "npm" # Change this based on your dependency type
    directory: "/" # Adjust based on where your dependencies are
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
